---
name: ShareFare CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install modules
        working-directory: ShareFare
        run: npm i
      - name: Run ESLint
        working-directory: ShareFare
        run: npm run lint
      - name: Run Prettier
        working-directory: ShareFare
        run: npm run format:check
